services:
  client:
    build: ./src/client
    container_name: sorter_client_${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ${APP_SRC_PATH}/sorter/src/client:/usr/local/app
  server:
    build: ./src/server
    container_name: sorter_server_${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      FLASK_RUN_PORT: ${SERVER_PORT}
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_FILE_PATH: ${DATABASE_FILE_PATH}
      GOOGLE_APP_CLIENT_ID: ${GOOGLE_APP_CLIENT_ID}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ${APP_SRC_PATH}/sorter/src/server:/usr/local/app
      - ${APP_SRC_PATH}/sorter/data:/usr/local/app/data
